name: app-room docker
on:
  push:
    branches:
    - master
  release:
    types: [published]
  pull_request:
    branches:
    - master
jobs:
  build:
    name: build and push
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v2
    
      - name: build
        run: docker build --no-cache --tag pionwebrtc/ion:latest-app-room -f docker/app-room.Dockerfile .

      - name: login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: tag
        if: github.event_name == 'release'
        run: docker tag pionwebrtc/ion:latest-app-room pionwebrtc/ion:"$TAG"-app-room
        env:
          TAG: ${{ github.event.release.tag_name }}

      - name: push
        if: github.event_name == 'release'
        run: docker push pionwebrtc/ion:"$TAG"-app-room
        env:
          TAG: ${{ github.event.release.tag_name }}

      - name: push-master
        run: docker push pionwebrtc/ion:latest-app-room
